### ISSUE TITLE
Can not generate PDF

### ISSUE THREAD

**Issue by colleenfyj** [mohuangrui/ucasthesis#106] opened 2019-02-14 02:54 UTC
[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/2863084/Thesis.log)

One attachment is the log file after executing artratex.bat.
Another attachment is the error/warning when executing artratex.bat.
Please help. Thank you!

![default](https://user-images.githubusercontent.com/30891518/52759467-eb989480-3046-11e9-825c-221410cafd4f.PNG)

**Comment by mohuangrui** [comment] 2019-02-14 04:11
Hello,

1. You'd better avoid using Chinese characters in the names of folders.
2. The log file you sent me was generated by pdflatex, while the screenshot shows xelatex...
3. According to the errors in the log file, such as:
```
! LaTeX Error: File `newtxtext.sty' not found.
```
the failure was caused by missing packages. MikTeX usually can install missing packages automatically, please try to compile several times to see whether the problem will be solved. If not, please install the missing packages such as newtxtext.sty, newtxmath.sty manually. Or, you can choose to install TexLive2018 instead of MikTeX.
4. The error of the artratex.bat was caused by missing pdf, which was not generated by the failed compilation.
Cheers!

**Comment by mohuangrui** [comment] 2019-02-14 04:14
For your further reference, please see [编译指南](https://github.com/mohuangrui/ucasthesis/wiki/编译指南)

**Comment by colleenfyj** [comment] 2019-02-15 08:05
(1)I downloaded the install package from this https://www.tug.org/texlive/acquire-netinstall.html, it is not TexLive but MikTeX? （.exe does not apply to my computer os of win7, so I used the .zip file to install）
![default](https://user-images.githubusercontent.com/30891518/52842773-16fcab80-313b-11e9-81fc-493321f74d8b.PNG)

(2)where Can I find this package manager?
![default](https://user-images.githubusercontent.com/30891518/52842888-70fd7100-313b-11e9-852c-8e021180cbe7.PNG)

(3) I have tried the latexspine, and it worked.

**Comment by mohuangrui** [comment] 2019-02-20 02:52
1) I cannot help with your software installation. Please either read the instructions more carefully to figure it out by yourself or to ask help from your officemates who are familiar with LaTeX.

2) Please make sure do not install both MikTeX and Texlive. You have to uninstall the old one before installing a new one.

3) Your problem was caused by missing packages, for which latexspine does not requires. I'm sure that ucasthesis will compile smoothly if you correctly installed the required software. Therefore, I will now close this issue.

Cheers.

**Closed by mohuangrui** 2019-02-20 02:52 UTC
